title: 哥布林民族的究极神圣炫酷罗马帝国国家档案馆
author: 哥布林民族的究极神圣炫酷罗马帝国立法院
email: jiaobenhaimo@outlook.com
description: 
 为全体国民提供诏书及其他信息的查询服务
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 哥布林民族的究极神圣炫酷罗马帝国国家档案馆
  tagline: 为全体国民提供诏书及其他国家信息的查询服务
  date_format: "%Y年%m月%d日"
  style: black
  showNav: false
  showPicker: false

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

plugins:
  - jekyll-seo-tag
#  - jekyll-feed